package com.wakesync.network.model

import kotlinx.serialization.Serializable

/**
 * Strict 4-field post-session insight request (RF-INS-01, RNF-INS-01).
 * Never contains heart rate, score, coordinates, raw signals, or session start timestamp.
 */
@Serializable
data class InsightRequestDto(
    val sessionType: String,
    val durationSeconds: Int,
    val restLatencySeconds: Int?,
    val outcome: String
)

/**
 * Insight text generated by Google Gemini via wakesync-gateway (RF-INS-01, Appendix F.3).
 */
@Serializable
data class InsightResponseDto(
    val insight: String
)
